name: servicex_client_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2


#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_native_splash: ^2.4.7
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  pinput: ^5.0.2
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  video_player: ^2.10.1
  chewie: ^1.13.0
  flutter_calenders: ^1.0.0
  table_calendar: ^3.2.0
  syncfusion_flutter_calendar: ^31.2.16
  percent_indicator: ^4.2.5
  easy_date_timeline: ^2.0.9
  file_picker: ^10.3.8
  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  flutter_lucide: ^1.7.0


  # State Management
  get: ^4.7.2


  # Product Specific
  custom_navigation_bar: ^0.8.2
  image_picker: ^1.2.1

# Auth
  firebase_auth: ^5.3.1

# Firestore
  cloud_firestore: ^5.4.4

# Storage (chat media, profile images, job photos)
  firebase_storage: ^12.3.2

# Push notifications (optional but matches your UI)
  firebase_messaging: ^15.1.3

# Crash + analytics (optional, production)
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3









  #--------------- ./ PACKAGES END ------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true





  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/videos/
    - assets/images/





  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
